# Generated by Django 5.0 on 2023-12-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_logedin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logedin',
        ),
    ]
