# Generated by Django 5.0 on 2023-12-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('heroname', models.CharField(max_length=100)),
                ('no_of_hits', models.IntegerField()),
            ],
        ),
    ]
